sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mJgQ7IKU70Ql9CLKDsaFKD6M7Fh+80aApSrT0h7NFk6sLuEBY0IO/I7iuRp9t/vSFy01h4mbdUNW2s+sDCMisDLqz6lkSyP5YwZeT5pACpwFGO/8UgUULZVBgCQhacsSIDo67qc3aCDfWOOumwXiMXFwnxILfRQ1a5K5UvrFmab7poP125A/+lVzkxvfJDQBbOgst6IUotzT/Sdsp5W7MRUqvumAgaYj5+bVKFA5WUp+Iyxj4tT6e1x93KYMGOSSHB6cyqxqL6uP+fYF57Z0Amdr+5LWzq8nKQ6Ms+KmjtCnUOxsg1ThiDDS+rxZIm898C+MX9vGDUGDdWV5319wHf6TbW/Np9pY9/6u/UATQXSWx1KMBylwIiJ0RUAoxrKkY62Gp5vdZT7ovuPhJO/qzZyi/BkxkZKkiw4UJNoQ6btWgPfwk7Ko89DG5Z5md2Lxoe7kJF5BT9SoKNlHonqJjlwSybiyiDNv/iMRlOx/ZjUD9Lt6xzgn7/VcagvD3Ox4HqPvLwzMui1Du2RZF6NloTTzWpLnmtpPmqNk4UBxyetdiraPSiy1J9Qeyejd7YxcNlhCJhJiOH38xBcfDPllQkGyeexr/4e93IXCgQlsk8kn7opBQ5dOiXWtN0itG9OREUOSq62L74ICV8HPvxW8QbJ8conUC7LVF/V+rV4yE6c=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/State-of-the-Union-Addresses_5045
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy